# -*- coding: utf-8 -*-
"""GOOGLE MAP API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfqoHY56jkKx2hPT20akpORBZZzN3i6s
"""

import requests

def googlemap_search(place):
  url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=" + place + "&inputtype=textquery&" + "fields=formatted_address%2Cphotos%2Crating%2Ctypes" + "&key=AIzaSyAcRNmLl5V8WpQDzJCn2zorQLh6FXeV9Dw"
  payload={}
  headers = {}
  response = requests.request("GET", url, headers=headers, data=payload)
  
  print(response.text)
  return response.text

googlemap_search("Starbucks Bongeunsa Station Branch")

